### ISSUE TITLE
Convert into an Nx workspace for easier building/developing

### ISSUE THREAD

**Issue by yharaskrik** [jevakallio/jest-clean-console-reporter#2]
Thoughts on converting this into an Nx workspace to easily support typescript, building and packaging?

I am currently working on switching this package to using TypeScript and it would make it easier to dev for sure!

**Comment by jevakallio** [comment]
Hi @yharaskrik! Thanks for the suggestion. As Nx is a monorepo tool, and this package is just a single package with a few code files, it's is not appropriate here IMO.

We can discuss the TypeScript migration at #3!
