### ISSUE TITLE
Feature Idea: Support flags for showing all the errors

### ISSUE THREAD

**Issue by jamenamcinteer** [jevakallio/jest-clean-console-reporter#4]
I think it would be useful if it were possible to show all the error details with a flag, something like `yarn test --showErrorDetails`, if someone wanted to see the raw console output again without modifying the config.

**Comment by jevakallio** [comment]
@jamenamcinteer I like the idea, but I'm not aware of a way of passing flags to jest, which then would pass it to the reporter. They get caught by jest's own arg validator. If you have ideas how to achieve this, I'd be open to bringing this feature onboard.

In the meantime, if you normally would be using only the default reporter stack, you can choose to not load our reporter like this:

```
yarn test -- --reporters=default
```

**Comment by jamenamcinteer** [comment]
That makes sense, I'm not super familiar with how jest works under the hood. Thanks for the workaround!
