### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module FILEPATH not supported.

### ISSUE THREAD

**Issue by valdoryu** [jevakallio/jest-clean-console-reporter#9]
Hello,

Using your package on Node 16 with babel 7.16 raises this error

![Capture d’écran 2022-01-06 à 13 57 07](https://user-images.githubusercontent.com/7875009/148386427-da621ccf-022a-4549-a305-29d9ab846ff3.png)

Apparently it comes from the require('chalk') line in getLogGroupSummary.js
Do you have any insight on the question ?

Thanks !

**Comment by SimenB** [comment]
https://github.com/jevakallio/jest-clean-console-reporter/blob/f4db2900475cf96f3d5b9f81c009f0f55c962f05/package.json#L13

`chalk@5` is not supported, range here should be updated. If you have a lockfile you can try to replace chalk v5 with v4 (or v3)

**Comment by valdoryu** [comment]
So I have to manually write 3.0.0 in package-lock.json to make it work ?

**Comment by SimenB** [comment]
![image](https://user-images.githubusercontent.com/1404810/152838004-ac5c0d79-fb42-4d35-a33a-ce26615758e9.png)

you do via this module, as mentioned the range here is wrong

**Comment by valdoryu** [comment]
I confirm that changing
```
      "requires": {
        "chalk": ">=5.0.0"
      },
      "dependencies": {
        "chalk": {
          "version": "5.0.0",
          "resolved": "https://registry.npmjs.org/chalk/-/chalk-5.0.0.tgz",
          "integrity": "sha512-/duVOqst+luxCQRKEo4bNxinsOQtMP80ZYm7mMqzuh5PociNL0PvmHFvREJ9ueYL2TxlHjBcmLCdmocx9Vg+IQ==",
          "dev": true
        }
      }
```

to 

```
      "requires": {
        "chalk": ">=3.0.0"
      },
      "dependencies": {
        "chalk": {
          "version": "3.0.0",
          "resolved": "https://registry.npmjs.org/chalk/-/chalk-3.0.0.tgz",
          "dev": true
        }
      }
```

and `npm i` works

**Comment by okeeffed** [comment]
For anyone who is using Yarn with resolutions support at their workplace, I worked around this with [resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/).

My `package.json` file:

```json
{
	// ... rest omitted for brevity
	"resolutions": {
    	"jest-clean-console-reporter/**/chalk": "^3.0.0 || ^4.0.0"
  	},
}
```

I couldn't find a native NPM equivalent, but apparently there are other 3rd party options to help with this (although sounds like more of a workaround than it is worth until that other PR is merged).

**Comment by gnapse** [comment]
If I do what's mentioned in https://github.com/jevakallio/jest-clean-console-reporter/issues/9#issuecomment-1044628479, and then run `npm i`, it overwrites what I changed in my lock file.

I wonder if there's a less hacky way to fix this. Ideally, the fix should be in this package, updating the peer dependency to not allow chalk v5, and have a new release. But this library seems abandoned, right? It's been 2 years since it was last updated apparently.

**Comment by pionxzh** [comment]
For NPM users, this is the workaround.

```json5
//package.json

  "overrides": {
    "jest-clean-console-reporter": {
      "chalk": "^4.1.2"
    }
  },
```
